travis:
  secure:
    BINSTAR_TOKEN: qb+h5ENXgOJAlIBCJaXnkS7p8WdEQgN4n/IRo0y3qh4V+yMotMlwF0yU2loNDIHSNvYaENBN2kOW9EtR9FHUkettY8KVRKR4AEjz1oIvnWbzLCFiDEpFS2d1uz3746Bf5ZlxuToOhs1xJZE+LPuKNNAWBOcffsTTgX7wcpZixIX4/cqu75denDx3US6TzvzUCbC2ZQtw5YDGMjhqlGbTleuoayDPrpLIn/eOGQ4S1j1tgJXhNrPSF70k1d/UDtgOR5GMjuza146MsSHEcQURufxmo1S2C6/lSHz9LheJnbqYPVhI+vmZKaDlg+yodVvB5NRfaD3b63qqZzuJLC2QDPrCYsftrYSUWHTMgFGHd6zc7wAUVjjuZCDQCNNbqrGZwvSnKlv9FTBo76NWTmir7zKhhkEwth+QwWbcsdczI3Ty7IfcrwjKackLY1YQ48BIqKDKUgSEQFu0zMVoei53NXcoPteJki60HtGqJLlmhq6fcYsUWz6ZZhHF3tTXfLFr/hLCWzryK/d07dNmhVL/ZRsA3hu8hS1LhPAQQAPh58CWgIL4IKHWWp9BwtXqcjLD8IYPhOIfwktuWPBljyvKYd18E/HNPWnHvYeB3uyWjnbyYbzCgowftVZq3iPDjXqLTOFHW224c/tQOuTP0SZxIu4fagMsUGsoZkGF7RFHjFI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
